package com.ms.EMPSERVICE.pojo;
// Generated 23 Nov, 2024 10:52:34 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Acct generated by hbm2java
 */
@Entity
@Table(name = "acct", catalog = "hrdept")
public class Acct implements java.io.Serializable {

	private Integer acctId;
	private String ctc;
	private String salary;
	private Date date;

	public Acct() {
	}

	public Acct(String ctc, String salary, Date date) {
		this.ctc = ctc;
		this.salary = salary;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "acct_id", unique = true, nullable = false)
	public Integer getAcctId() {
		return this.acctId;
	}

	public void setAcctId(Integer acctId) {
		this.acctId = acctId;
	}

	@Column(name = "ctc", length = 45)
	public String getCtc() {
		return this.ctc;
	}

	public void setCtc(String ctc) {
		this.ctc = ctc;
	}

	@Column(name = "salary", length = 45)
	public String getSalary() {
		return this.salary;
	}

	public void setSalary(String salary) {
		this.salary = salary;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
