package com.ms.EMPSERVICE.pojo;
// Generated 23 Nov, 2024 10:52:34 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Emp generated by hbm2java
 */
@Entity
@Table(name = "emp", catalog = "hrdept")
public class Emp implements java.io.Serializable {

	private Integer empid;
	private Address address;
	private String name;
	private Integer acctId;
	private Integer projectId;

	public Emp() {
	}

	public Emp(Address address, String name, Integer acctId, Integer projectId) {
		this.address = address;
		this.name = name;
		this.acctId = acctId;
		this.projectId = projectId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "empid", unique = true, nullable = false)
	public Integer getEmpid() {
		return this.empid;
	}

	public void setEmpid(Integer empid) {
		this.empid = empid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Address_id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "acct_id")
	public Integer getAcctId() {
		return this.acctId;
	}

	public void setAcctId(Integer acctId) {
		this.acctId = acctId;
	}

	@Column(name = "project_id")
	public Integer getProjectId() {
		return this.projectId;
	}

	public void setProjectId(Integer projectId) {
		this.projectId = projectId;
	}

}
